config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  resources :users, only: [:index, :show] do
    resources :posts, only: [:index, :show, :new, :create, :destroy] do
      resources :comments, only: [:new, :create, :destroy]
      resources :likes, only: [:create]
    end
  end
  # Defines the root path route ("/")
  # root "articles#index"
  root 'users#index', as: 'home'
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable
  has_many :comments, class_name: 'Comment', foreign_key: 'user_id'
  has_many :likes, class_name: 'Like', foreign_key: 'user_id'
  has_many :posts, class_name: 'Post', foreign_key: 'author_id'

  validates :name, presence: true
  validates :posts_counter, presence: true, numericality: { only_integer: true, greater_than_or_equal_to: 0 }
  def admin?
    role == 'admin'
  end

  def recent_post
    posts.order(created_at: :desc).limit(3)
  end
end

app/controllers/users_controller.rb
require_relative '../models/user'
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/index.html.erb
  <div class="user_list_section">
    <% @users.each do |user| %>
      <%= render partial: 'partial/user', locals: { user: user } %>
    <% end %>
  </div>

app/views/users/show.html.erb
<section class="show_user_section">
  <div class="user_infos">
    <img src=<%= @user.photo %> alt=<%= @user.name %> class="user_avatar">
    <div class="auser_details">
      <h3 class="user_name"><%= link_to @user.name, user_path(id: @user.id) %></h3>
      <p class="user_post_counter">
        Number of posts: <b> <%= @user.posts_counter %></b>
      </p>
    </div>
  </div>
  <div class="user_bio">
    <p class="div_title">Bio </p>
    
    <p class="div_content"><%= @user.bio %></p>
  </div>
  <div class="post_list">
      <% @user.posts.each do |post| %>
      <%= render partial: "partial/like", locals: { like: Like.new, post_id: post.id, user_id: post.author_id } %>
        <%= render partial: 'partial/post', locals: { post: post } %>
      <% end %>
     
  </div>
   <%= link_to "See all posts", user_posts_path(user_id: @user.id), class: "button"%>
   <%= link_to "Create Post", new_user_post_path(user_id: @user.id), class: "button"%>
</section>