config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  resources :users, only: [:index, :show] do
    resources :posts, only: [:index, :show, :new, :create, :destroy] do
      resources :comments, only: [:new, :create, :destroy]
      resources :likes, only: [:create]
    end
  end
  # Defines the root path route ("/")
  # root "articles#index"
  root 'users#index', as: 'home'
end

app/views/partial/_comment.html.erb
<%=  User.find(comment.user_id).name %> : <%= comment.text%> <br>

app/views/partial/_form.html.erb
<%= form_with model: @post, method:"post", url: user_posts_path, class:"form", local: true do |form| %>
  <%= form.text_field  :title , class: "form_input" , placeholder: "Post Title "%>
  <%= form.text_area :text , class: "form_text_area", placeholder: "Post Content " %>
  <%= form.submit "Save" , class: "form_button button"%>
<% end %>

app/views/partial/_like.html.erb
  <%= form_with model: @like, url: user_post_likes_path(user_id: user_id, post_id: post_id),class: "form", local: true do |form| %>
  <%= form.submit "Like", class: "button" %>
  <% end %>

app/views/partial/_post.html.erb
<div class="user_post">
    <%= link_to post.title, user_post_path(user_id: post.author_id,id: post.id), class: "div_title" %>
  <p class="div_content">
    <%= post.text %>
  </p>
  <p class="div_footer">
    Comments: <%= post.comments_counter %> , Likes: <%= post.likes_counter %>
  </p>
  <% if can? :delete, post %>
    <%= link_to "Delete Post",user_post_path(user_id: post.author_id, id: post.id),class:"button",  data: { turbo_method: :delete } %>
  <% end %>
</div>

app/views/partial/_user.html.erb
  <div class="user_container">
  <img src=<%= user.photo %> alt=<%= user.name %> class="user_avatar">
  <div class="user_details">
    <h3 class="user_name"><%= link_to user.name, user_path(id: user.id) %></h3>
    <p class="user_post_counter">
      Number of posts: <b> <%= user.posts_counter %></b>
    </p>
  </div>
</div>