config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  resources :users, only: [:index, :show] do
    resources :posts, only: [:index, :show, :new, :create, :destroy] do
      resources :comments, only: [:new, :create, :destroy]
      resources :likes, only: [:create]
    end
  end
  # Defines the root path route ("/")
  # root "articles#index"
  root 'users#index', as: 'home'
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user, class_name: 'User', foreign_key: 'author_id'
  has_many :comments, class_name: 'Comment', foreign_key: 'post_id'
  has_many :likes, class_name: 'Like', foreign_key: 'post_id'

  validates :title, presence: true, length: { in: 3..250 }
  validates :comments_counter, presence: true, numericality: { only_integer: true, greater_than_or_equal_to: 0 }
  validates :likes_counter, presence: true, numericality: { only_integer: true, greater_than_or_equal_to: 0 }

  after_save :update_posts_counter
  after_destroy :decrease_post_counter

  def update_posts_counter
    user.increment!(:posts_counter)
  end

  def decrease_post_counter
    user.decrement!(:posts_counter)
  end

  def recent_comments
    comments.order(created_at: :desc).limit(5)
  end
end

app/controllers/api/posts_controller.rb
require 'jwt'

class Api::PostsController < Api::ApplicationController
  before_action :find_user, only: [:index]

  def index
    if @user
      @posts = @user.posts.order(created_at: :asc)
      render json: @posts
    else
      render json: { status: 'Failure', error: 'User Not Found' }
    end
  end

  private

  def find_user
    @user = User.find_by_id(params[:user_id])
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  load_and_authorize_resource
  def index
    @user = User.find(params[:user_id])
    @posts = @user.posts
  end

  def show
    @user = User.find(params[:user_id])
    @post = @user.posts.find(params[:id])
  end

  def new
    @current_user = current_user
    @post = Post.new
    puts 'getting out of the new method'
  end

  def create
    @post = Post.new(post_params)
    @post.author_id = current_user.id

    respond_to do |format|
      if @post.save
        format.html { redirect_to user_path(current_user.id) }

      else
        render :new
      end
    end
  end

  def destroy
    @post = Post.find(params[:id])
    if @post.destroy
      redirect_to user_posts_path(current_user.id), notice: 'Post was successfully destroyed.'
    else
      flash.new[:alert] = @post.errors.full_messages.first if @post.errors.any?
      render :show, status: 400
    end
  end

  private

  def post_params
    params.require(:post).permit(:title, :text)
  end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/index.html.erb
<section class="show_user_section">
  <div class="user_infos">
    <img src=<%= @user.photo %> alt=<%= @user.name %> class="user_avatar">
    <div class="auser_details">
      <h3 class="user_name"><%= link_to @user.name, user_path(id: @user.id) %></h3>
      <p class="user_post_counter">
        Number of posts: <b> <%= @user.posts_counter %></b>
      </p>
    </div>
  </div>
  <div class="user_bio">
    <p class="div_title">Bio </p>
    
    <p class="div_content"><%= @user.bio %></p>
  </div>
  <div class="post_list with_comments">
      <% @user.posts.each do |post| %>
      <%= render partial: "partial/like", locals: { like: Like.new, post_id: post.id, user_id: post.author_id } %>
        <%= render partial: 'partial/post', locals: { post: post } %>
        <div class="comment_list">
          <% post.recent_comments.each do |comment| %>
            <%= render partial: 'partial/comment', locals: { comment: comment } %>
          <% end %>
        </div>
      <% end %>
     
  </div>
   <%= link_to "Pagination", user_posts_path(user_id: @user.id), class: "button"%>
</section>

app/views/posts/new.html.erb
<section class="add_form_section">
  <%= render partial: 'partial/form', locals: { post: @post } %>
</section>

app/views/posts/show.html.erb
<section class="show_user_section">
  <div class="post_list with_comments">     
      <div class="user_post">
        <div class="post_header">
          <%= link_to @post.title.concat(' By ').concat(@user.name), user_post_path(user_id: @post.author_id,id: @post.id), class: "div_title" %>
          <div class="details">
            Comments: <%= @post.comments_counter %> , Likes: <%= @post.likes_counter %>
          </div>
        </div>
        
      <p class="div_content">
        <%= @post.text %>
      </p>
      <p class="div_footer">
        Comments: <%= @post.comments_counter %> , Likes: <%= @post.likes_counter %>
      </p>
      </div>
      <div class="comment_list">
        <% @post.comments.includes(:post).each do |comment| %>
          <%= render partial: 'partial/comment', locals: { comment: comment } %>
          <% if can? :delete, comment %>
            <%= link_to "Delete Comment", user_post_comment_path(user_id: comment.author.id, post_id: comment.post.id, id: comment.id),class:"button", data: { turbo_method: :delete } %>
          <% end %>
        <% end %>
      </div>
      <%= link_to "Add Comment", new_user_post_comment_path(user_id: @user.id, post_id: @post.id), class: "button"%>
     
  </div>
</section>